import "./globals.css";
import Smoth from './component/Smoth';
import  CursorMotion from './component/CursorMotion';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Smoth>
         <div className="hidden md:block">  <CursorMotion /></div>
          {children}
        </Smoth>
      </body>
    </html>
  );
}
